// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAljes2YK245_G20pV30ucMhfjddARe9bU',
    appId: '1:830707562193:web:4a09dd088e5a7a340b37f0',
    messagingSenderId: '830707562193',
    projectId: 'ecomapp-b1f96',
    authDomain: 'ecomapp-b1f96.firebaseapp.com',
    storageBucket: 'ecomapp-b1f96.appspot.com',
    measurementId: 'G-0YCFWKQRHH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzb8YLRWYzvPigMie38-KM0nsaW7BbAFA',
    appId: '1:830707562193:android:ea013d700a21f4960b37f0',
    messagingSenderId: '830707562193',
    projectId: 'ecomapp-b1f96',
    storageBucket: 'ecomapp-b1f96.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAljes2YK245_G20pV30ucMhfjddARe9bU',
    appId: '1:830707562193:web:1a29f89042b78bb70b37f0',
    messagingSenderId: '830707562193',
    projectId: 'ecomapp-b1f96',
    authDomain: 'ecomapp-b1f96.firebaseapp.com',
    storageBucket: 'ecomapp-b1f96.appspot.com',
    measurementId: 'G-L4CDVVDKHH',
  );
}
